Repository mju-likelion/eclair, pull requests merged in 2024-02, with the labels that each got.

#2 [Feature/#1] project setting
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/ApplicationView.js
  src/pages/LogIn.js
  src/pages/Main.js
  src/setupTests.js
  yarn.lock
Labels: ⚙️ setting

#3 [Feature/#1] Axios 세팅
  src/api/Axios.js
Labels: ⚙️ setting

#8 [Feature/#4] 메인페이지 파트별 지원서 조회 기능 구현
  src/MainDummy.json
  src/api/getApplication.js
  src/api/postLogin.js
  src/pages/Main.js
Labels: 💖 Feature

#6 [Feature/#5] login 페이지 구현
  package.json
  src/App.js
  src/api/postLogin.js
  src/pages/LogIn.js
  src/pages/Main.js
  yarn.lock
Labels: 💖 Feature

#13 [Feature/#12] api 요청 시 로그인 상태가 반영되지 않도록 수정
  package.json
  src/pages/Main.js
  yarn.lock
Labels: 🔨 bug

#15 [Feature/#14] 합격자 지원서 필터링 버튼 기능 구현
  src/api/getApplication.js
  src/pages/Main.js
Labels: 💖 Feature

#11 [feature/#7] introduction-page 구현
  package.json
  src/App.js
  src/api/getIntroduction.js
  src/pages/ApplicationView.js
  src/pages/Introduction.js
  yarn.lock
Labels: 💖 Feature

#18 [Feature/#17] 해당 지원서의 자기소개서를 조회하는 페이지로 이동
  src/pages/Main.js
Labels: 💖 Feature
